before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      # Disables debug symbols (-s, -w), passes version information
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
universal_binaries:
  - replace: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: haimgel
    name: screendaemon
brews:
  - tap:
      owner: haimgel
      name: homebrew-tools
    name: screendaemon
    homepage: "https://github.com/haimgel/screendaemon"
    description: "MQTT to command-line applications gateway."
    folder: Formula
    install: |
      bin.install "screendaemon"
    service: |
      run [opt_bin/"screendaemon"]
    test: |
      assert_match /Usage of/, shell_output("#{bin}/screendaemon -h", 0)

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
