app-id: "mqtt2cmd"
mqtt:
  broker: "tcp://localhost:1883"
  username: "your_mqtt_username"
  password: "your_mqtt_password"

displays:
  - name: "Monitor 1"
    refresh: "1m"
    get_state: "ddcutil getvcp 0x60"
    inputs:
      - name: "VGA-1"
        set_value: "ddcutil setvcp 0x60 0x01"
      - name: "VGA-2"
        set_value: "ddcutil setvcp 0x60 0x02"
      - name: "DVI-1"
        set_value: "ddcutil setvcp 0x60 0x03"
      - name: "DVI-2"
        set_value: "ddcutil setvcp 0x60 0x04"
      - name: "Composite-1"
        set_value: "ddcutil setvcp 0x60 0x05"
      - name: "Composite-2"
        set_value: "ddcutil setvcp 0x60 0x06"
      - name: "S-Video-1"
        set_value: "ddcutil setvcp 0x60 0x07"
      - name: "S-Video-2"
        set_value: "ddcutil setvcp 0x60 0x08"
      - name: "Tuner-1"
        set_value: "ddcutil setvcp 0x60 0x09"
      - name: "Tuner-2"
        set_value: "ddcutil setvcp 0x60 0x0a"
      - name: "Tuner-3"
        set_value: "ddcutil setvcp 0x60 0x0b"
      - name: "Component-1"
        set_value: "ddcutil setvcp 0x60 0x0c"
      - name: "Component-2"
        set_value: "ddcutil setvcp 0x60 0x0d"
      - name: "Component-3"
        set_value: "ddcutil setvcp 0x60 0x0e"
      - name: "DisplayPort-1"
        set_value: "ddcutil setvcp 0x60 0x0f"
      - name: "DisplayPort-2"
        set_value: "ddcutil setvcp 0x60 0x10"
      - name: "HDMI-1"
        set_value: "ddcutil setvcp 0x60 0x11"
      - name: "HDMI-2"
        set_value: "ddcutil setvcp 0x60 0x12"

log:
  path: "/workspace/internal/config/logs/screendaemon.log"
